# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8703b76a8496605c4a61be6665a07788f878619e8b66e6ce900746c19b5c90bdfe8272cb38b8ec058e64ac42a19034ee9d9353b542df888d128264f9f9300cd6

test:
  secret_key_base: ed4b33fde6c459dbe693485daa6ac46bd5925a21241812ef995444fb7b90779d65b540b67f2e8c7e383fedc4f4a04b557cabdf5e9ef5b741c8795469a3a1dfee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
